name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/airjorden.png
   - assets/eclips.png
   - assets/json/men_shoes.json
   - assets/json/kids_shoes.json
   - assets/json/female_shoes.json
   - assets/shoes/2.png